wall follow action and simulated battery
iRobotEducation/create3_sim pull request #122
Opened 2021-10-30 01:29 UTC by justinIRBT

## Description

Added action server with simple wall follow behavior

Simulated battery charge/discharge

Fixes # (issue).
https://github.com/iRobotEducation/create3_sim/issues/38
https://github.com/iRobotEducation/create3_sim/issues/117
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Tested wall following around AWS house
Tested battery charge/discharge on dock / off dock while driving and idle

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation

2021-10-30 10:33 UTC, alsora commented on irobot_create_toolbox/include/irobot_create_toolbox/motion_control/wall_follow_states.hpp
> +  : logger_{node_logging_interface->get_logger()}
minor: if you just need to create a logger, it's probably better to pass the logger rather than the node logging interface

2021-10-30 11:05 UTC, alsora commented on irobot_create_toolbox/src/mock_publisher.cpp
> +  battery_state_msg_.capacity = 2.046;
let's use some const for these numbers, similarly to the others

2021-10-30 11:42 UTC, alsora commented on irobot_create_toolbox/src/motion_control/wall_follow_behavior.cpp
> +  if (wf_running_) {
we should probably check also `if (behavior_scheduler_->has_behavior)` and reject a goal in this case.
note that if a goal is already running, this would also be detected by `const bool ret = behavior_scheduler_->set_behavior(data);` but I think is better to reject the goal rather than cancelling it immediately

2021-10-30 12:05 UTC, alsora commented on irobot_create_toolbox/src/motion_control/wall_follow_behavior.cpp
> +        wf_side = irobot_create_msgs::action::WallFollow::Goal::FOLLOW_RIGHT;
rather than having a default here, it would be better to have it in the action definition https://github.com/iRobotEducation/irobot_create_msgs/blob/main/action/WallFollow.action#L5
```
int8 follow_side -1
```
p.s. maybe it's possible to use FOLLOW_RIGHT as default value rather than the number but I'm not sure

2021-10-30 12:06 UTC, alsora commented on irobot_create_toolbox/src/motion_control/wall_follow_behavior.cpp
> +      RCLCPP_INFO(logger_, "Starting wall follow goal with side %d", static_cast<int>(wf_side));
it may be better to say left/right rather than 1/-1

2021-10-30 12:07 UTC, alsora commented on irobot_create_toolbox/src/motion_control/wall_follow_behavior.cpp
> +  std::shared_ptr<const irobot_create_msgs::action::WallFollow::Goal>/*goal*/)
what if the goal has a duration of 0? do we accept it with a warning or do we reject it?

2021-10-30 12:12 UTC, alsora commented on irobot_create_toolbox/src/motion_control/wall_follow_states.cpp
> +          // This behavior won't be instantiated by state machine
should we have a warning/assert here?

2021-10-30 12:15 UTC, alsora commented on irobot_create_toolbox/src/motion_control/wall_follow_states.cpp
> +    // Return that we are no longer running
it looks like the code assumes that the hazard is a bump, but in `WallFollowBehavior::hazard_vector_callback(` you are also including cliffs, stalls and wheel drops.
Since the algorithm uses IR servoing, shouldn't we use only bumps?

2021-11-01 11:45 UTC, eborghi10 requested changes

2021-11-01 11:45 UTC, eborghi10 commented on irobot_create_toolbox/src/mock_publisher.cpp
> +  return docked_charge;
You can probably declare `docked_charge` amd `time_docked` as `const` above.

```suggestion
  return std::min(docked_charge, 1.0);
```

2021-11-01 17:11 UTC, justinIRBT commented on irobot_create_toolbox/src/motion_control/wall_follow_states.cpp
> +    // Return that we are no longer running
Wall follow will still work for cliffs, I assumed we would also want the robot to back away and rotate for the other hazards as well.

2021-11-01 17:44 UTC, justinIRBT commented on irobot_create_toolbox/src/motion_control/wall_follow_behavior.cpp
> +  if (wf_running_) {
This is currently consistent with the robot behavior, if we change it here, we should change it on the robot.  One awkward thing here vs. robot is that reflexes are implemented as behaviors here, so if a reflex is running, it would reject the goal (it will still reject it later if the reflex hasn't finished before the start is run).  Admittedly, that is a race condition that may not be worth stressing over for the sim.

2021-11-01 18:10 UTC, justinIRBT commented on irobot_create_toolbox/src/motion_control/wall_follow_behavior.cpp
> +  std::shared_ptr<const irobot_create_msgs::action::WallFollow::Goal>/*goal*/)
I think its logical to run and succeed, as that is what the user asked for even though it doesn't make a lot of sense, that is what the behavior will currently do

2021-11-03 12:03 UTC, rjcausarano commented on irobot_create_toolbox/src/ir_intensity_vector_publisher.cpp
> +      this->msg_.readings.clear();
Why is this necessary?

2021-11-03 12:03 UTC, rjcausarano commented on irobot_create_toolbox/include/irobot_create_toolbox/ir_intensity_vector_publisher.hpp
> +  std::map<std::string, irobot_create_msgs::msg::IrIntensity> ir_intensities_;
Why do we need a map?

2021-11-03 12:05 UTC, rjcausarano commented on irobot_create_toolbox/src/ir_intensity_vector_publisher.cpp
> +      }
Why are these new lines needed?

2021-11-03 13:44 UTC, alsora commented on irobot_create_toolbox/src/motion_control/wall_follow_behavior.cpp
> +  if (wf_running_) {
You are right.
Let's ignore it for this ticket and eventually revisit it later

2021-11-03 16:41 UTC, justinIRBT commented on irobot_create_toolbox/include/irobot_create_toolbox/ir_intensity_vector_publisher.hpp
> +  std::map<std::string, irobot_create_msgs::msg::IrIntensity> ir_intensities_;
There was a race condition where occasionally the robot would publish an empty ir vector, which would mess up my wall follow logic.  The map persists the last readings for each sensor so every vector publication will have the last received readings.

2021-11-03 16:42 UTC, justinIRBT commented on irobot_create_toolbox/src/ir_intensity_vector_publisher.cpp
> +      }
See comment about race condition leading to empty vector

2021-11-03 16:53 UTC, justinIRBT commented
@eborghi10 @rjcausarano @alsora I am hoping to merge this today.  Does everything look good to go?

2021-11-03 16:59 UTC, eborghi10 approved these changes

2021-11-03 18:26 UTC, rjcausarano commented on irobot_create_toolbox/include/irobot_create_toolbox/ir_intensity_vector_publisher.hpp
> +  std::map<std::string, irobot_create_msgs::msg::IrIntensity> ir_intensities_;
Can the issue be solved by simply not publishing if `this->msg_.readings.empty()?`

2021-11-03 18:32 UTC, rjcausarano commented on irobot_create_toolbox/include/irobot_create_toolbox/ir_intensity_vector_publisher.hpp
> +  std::map<std::string, irobot_create_msgs::msg::IrIntensity> ir_intensities_;
Also the msg_.readings itself is a cache so I'm pretty sure it's already holding the information of the newly created map variable

2021-11-03 18:33 UTC, rjcausarano commented on irobot_create_toolbox/src/ir_intensity_vector_publisher.cpp
> +      }
Can we avoid adding this extra logic? I left a suggestion above

2021-11-03 19:34 UTC, justinIRBT commented on irobot_create_toolbox/include/irobot_create_toolbox/ir_intensity_vector_publisher.hpp
> +  std::map<std::string, irobot_create_msgs::msg::IrIntensity> ir_intensities_;
If the threads get out of sync, clearing in one place and populating in another could lead to populating the list twice between vector publishes or if the individual ir reading are out of sync it could not populate the full list.  The map ensures a stable list of all ir readings once and you get the most recent reading from each.

2021-11-03 20:13 UTC, rjcausarano commented on irobot_create_toolbox/include/irobot_create_toolbox/ir_intensity_vector_publisher.hpp
> +  std::map<std::string, irobot_create_msgs::msg::IrIntensity> ir_intensities_;
Can you please add a comment block in the code to explain this? Just by reading the code it is not easy to understand why we need this.

2021-11-03 20:14 UTC, rjcausarano commented on irobot_create_toolbox/include/irobot_create_toolbox/ir_intensity_vector_publisher.hpp
> +  std::map<std::string, irobot_create_msgs::msg::IrIntensity> ir_intensities_;
Also don't we need need to do the same map trick with hazards_vector_publisher?

2021-11-03 20:22 UTC, justinIRBT commented on irobot_create_toolbox/include/irobot_create_toolbox/ir_intensity_vector_publisher.hpp
> +  std::map<std::string, irobot_create_msgs::msg::IrIntensity> ir_intensities_;
I will add comments.  I thought about hazards_vector, but since it only publishes when things are present, we don't want to persist something that is no longer present.  We may want to do something in the future where we persist for a very short duration without re-enforcement, but I don't have a motivational case yet, like I did for wall follow issues with IR going away.  It could cause reflexes to stop prematurely, but we already have a min travel distance, so we might not see if in practice.

2021-11-04 18:23 UTC, rjcausarano commented
How is the user supposed to know what are the valid parameters that can be passed to the wall follow action? I had to look at the source code to figure out that 1 is follow left and -1 is follow right.

2021-11-04 18:43 UTC, justinIRBT commented
> How is the user supposed to know what are the valid parameters that can be passed to the wall follow action? I had to look at the source code to figure out that 1 is follow left and -1 is follow right.

@rjcausarano Its documented in the wall follow action message that the user will send in irobot_create_msgs.

2021-11-04 19:02 UTC, rjcausarano commented
> > How is the user supposed to know what are the valid parameters that can be passed to the wall follow action? I had to look at the source code to figure out that 1 is follow left and -1 is follow right.
> 
> @rjcausarano Its documented in the wall follow action message that the user will send in irobot_create_msgs.

Instead of displaying a message in the console saying "Invalid parameter", can it say what those valid parameters are? Like  "Expected values are either 1 for left of -1 for right"

2021-11-04 19:03 UTC, rjcausarano approved these changes
Approving but please consider my suggestion to prevent confusion

2021-11-04 23:22 UTC, justinIRBT commented
> > > How is the user supposed to know what are the valid parameters that can be passed to the wall follow action? I had to look at the source code to figure out that 1 is follow left and -1 is follow right.
> > 
> > 
> > @rjcausarano Its documented in the wall follow action message that the user will send in irobot_create_msgs.
> 
> Instead of displaying a message in the console saying "Invalid parameter", can it say what those valid parameters are? Like "Expected values are either 1 for left or -1 for right"

I don’t have my laptop with me, I will merge now and squeeze this more informative printout in next time I put up a PR

2021-11-04 23:23 UTC, merged