Adds cliffs to the kidnap logic. Creates a new node to publish the kidnap and the stop status.
iRobotEducation/create3_sim pull request #127
Opened 2021-11-02 15:53 UTC by LolaSegura

## Description

Creates a new node (`robot_status_publisher_node`) for publishing the `kidnap_status` and the `stop_status`. These topic were being published by the `mock_publisher_node`, but since they are publishing real values it was consider best to create a new node. 

This PR also includes the cliff sensors to the kidnap logic, that was preciously only taking into account the wheel drops. 

 Solves item 3 of #106.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Launch the robot using an empty world
``` #bash
   ros2 launch irobot_create_gazebo create3.launch.py 
```
and in a new terminal source and check that the mentioned node appear in the node list
``` #bash
   . install/local_setup.bash
   ros2 node list
```
Verify the `robot_status_publisher_node` info is the expected one. For this do:
``` #bash
   ros2 node info 
``` 
the output should look like this:
``` #bash
    /robot_status_publisher_node
       Subscribers:
          /clock: rosgraph_msgs/msgs/Clock
          /hazard_detection: irobot_create_msgs/msg/HazardDetectionVector
          /odom: nav+msgs/msg/Odometey
          /param_events: rcl_interfaces/msg/ParameterEvent
       Publishers:
         /kidnap_status: irobot_create_msgs/msg/KidnapStatus
         /parameter_events: rcl_interfaces/msg/ParameterEvent
         /rosout: rcl_interfaces/msg/Log
         /stop_status: irobot_create_msgs/msg/StopStatus
         . . .
```
## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2021-11-02 17:13 UTC, slowrunner commented
Question about kidnap status in the simulator:  How does a user simulate/invoke lift_and_move kidnapping the simulated bot?

2021-11-02 18:28 UTC, justinIRBT commented on irobot_create_toolbox/src/robot_status_publisher.cpp
> +: rclcpp::Node("robot_status_publisher_node")
We have a node on the robot called "robot_state" that is publishing all of the robot state data, for consistency, we should use that name here

2021-11-02 18:29 UTC, justinIRBT commented on irobot_create_toolbox/include/irobot_create_toolbox/mock_publisher.hpp
> -  rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr stop_status_subscription_;
This is going to conflict with my PR for wall follow and simulating more real battery status.  Perhaps my more real battery_status should also go into the new robot state node, but whichever PR merges first is going to cause conflicts for the other PR

2021-11-02 19:10 UTC, LolaSegura commented on irobot_create_toolbox/include/irobot_create_toolbox/mock_publisher.hpp
> -  rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr stop_status_subscription_;
Thank you for the heads up. I'll track the state of your PR then.

2021-11-02 19:11 UTC, LolaSegura commented
> Question about kidnap status in the simulator: How does a user simulate/invoke lift_and_move kidnapping the simulated bot?

That logic is aimed to be implemented by the end user.

2021-11-03 11:52 UTC, rjcausarano commented on irobot_create_toolbox/include/irobot_create_toolbox/robot_status_publisher.hpp
> +  void stop_callback(nav_msgs::msg::Odometry::SharedPtr msg);
Why did you decide to use odometry instead of the create3's own /wheel_vels topic?

2021-11-03 14:23 UTC, LolaSegura commented on irobot_create_toolbox/src/robot_status_publisher.cpp
> +: rclcpp::Node("robot_status_publisher_node")
Addressed

2021-11-03 14:29 UTC, LolaSegura commented on irobot_create_toolbox/include/irobot_create_toolbox/robot_status_publisher.hpp
> +  void stop_callback(nav_msgs::msg::Odometry::SharedPtr msg);
Since the odometry was mentioned in the [original issue](https://github.com/iRobotEducation/create3_sim/issues/54#issuecomment-921886335) I decided to use it. But it can be changed

2021-11-04 23:26 UTC, justinIRBT commented on irobot_create_toolbox/include/irobot_create_toolbox/mock_publisher.hpp
> -  rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr stop_status_subscription_;
My PR is merged.  The battery_state simulation used the docked and stopped information.  It might make sense to move the battery sim code to the robot_state node, otherwise you can add a subscription to the stop detection to the mock publisher to replace the Odom subscription that was detecting stopped used by the sim battery_state.  Let me know if you have any questions

2021-11-09 18:59 UTC, justinIRBT approved these changes

2021-11-11 12:20 UTC, rjcausarano commented
Can you please rename 'state' to 'status' in all file names? For consistency

2021-11-11 12:26 UTC, rjcausarano commented
Since this PR depends on https://github.com/iRobotEducation/create3_sim/pull/128, let's try to get that one merged first

2021-11-11 12:51 UTC, LolaSegura commented
> Can you please rename 'state' to 'status' in all file names? For consistency

It was [discuss](https://github.com/iRobotEducation/create3_sim/pull/127#discussion_r741362443) that the node name should be `robot_state`. 

Should I just rename everything o should I change the class name to `RobotSrate`?

2021-11-11 13:09 UTC, rjcausarano commented
> > Can you please rename 'state' to 'status' in all file names? For consistency
> 
> It was [discuss](https://github.com/iRobotEducation/create3_sim/pull/127#discussion_r741362443) that the node name should be `robot_state`.
> 
> Should I just rename everything o should I change the class name to `RobotState`?

Why? Does the real robot have a robot_state_node?

2021-11-11 13:10 UTC, rjcausarano commented
> > Can you please rename 'state' to 'status' in all file names? For consistency
> 
> It was [discuss](https://github.com/iRobotEducation/create3_sim/pull/127#discussion_r741362443) that the node name should be `robot_state`.
> 
> Should I just rename everything o should I change the class name to `RobotState`?

OK If we are following the same names as the robot then it's fine.

2021-11-16 18:33 UTC, eborghi10 requested changes

2021-11-16 18:33 UTC, eborghi10 commented on irobot_create_gazebo/launch/create3.launch.py
> +        executable='robot_state_publisher_node',
Can you rename the executable? It's quite similar to [this one](http://wiki.ros.org/robot_state_publisher).

2021-11-16 18:33 UTC, eborghi10 commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +        if (this->battery_state_msg_.percentage == 1.0f) {
`1.0f` should be a ROS parameter.

2021-11-16 18:33 UTC, eborghi10 commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +      if (this->battery_state_msg_.percentage > 0.9) {
Another target for ROS parameter here. Let's avoid hardcoded numbers.

2021-11-16 18:33 UTC, eborghi10 commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +void RobotState::kidnap_callback(irobot_create_msgs::msg::HazardDetectionVector::SharedPtr msg)
Can't we split all the code into different pieces? They don't seem to be related to each other.

2021-11-29 15:52 UTC, LolaSegura commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +void RobotState::kidnap_callback(irobot_create_msgs::msg::HazardDetectionVector::SharedPtr msg)
With this you mean the code from the `kidnap_callback()`?

2021-11-29 16:14 UTC, eborghi10 commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +void RobotState::kidnap_callback(irobot_create_msgs::msg::HazardDetectionVector::SharedPtr msg)
Yes,  can all the kidnap logic be hosted in a single kidnap_status node?

2021-11-29 16:18 UTC, LolaSegura commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +      if (this->battery_state_msg_.percentage > 0.9) {
Addressed

2021-11-29 16:18 UTC, LolaSegura commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +        if (this->battery_state_msg_.percentage == 1.0f) {
Addressed

2021-11-29 16:19 UTC, LolaSegura commented on irobot_create_gazebo/launch/create3.launch.py
> +        executable='robot_state_publisher_node',
Address

2021-11-29 16:22 UTC, alsora commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +void RobotState::kidnap_callback(irobot_create_msgs::msg::HazardDetectionVector::SharedPtr msg)
I think this was done because on the real robot we have a `robot-state-node` that publishes almost everything.
However, there the kidnap is computed elsewere (in an `_internal` hidden node) and then it's just republished here.

We should define whether we consider important to have matching ROS architecture on the robot and on the simulator (i.e. not only `ros2 topic list` shows the same topics, but also all topics are produced by the same nodes, etc).

My suggestion is probably to just move the kidnap logic somewhere else for now.
We can have the `irobot_toolbox` repo to provide a `KidnapEstimator` object that takes sensors as input and applies the logic we currently see here.

2021-12-09 19:02 UTC, LolaSegura commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +void RobotState::kidnap_callback(irobot_create_msgs::msg::HazardDetectionVector::SharedPtr msg)
Addressed

2021-12-10 11:52 UTC, eborghi10 commented
@LolaSegura is this PR ready for another review or do you need to work on something else?

2021-12-10 12:49 UTC, LolaSegura commented
@eborghi10 This is ready for another review

2021-12-13 15:32 UTC, eborghi10 requested changes

2021-12-13 15:32 UTC, eborghi10 commented on irobot_create_common_bringup/config/kidnap_estimator_params.yaml
> +    hazard_topic: /hazard_detection
```suggestion
    hazard_topic: /hazard_detection

```

2021-12-13 15:32 UTC, eborghi10 commented on irobot_create_common_bringup/config/robot_state_params.yaml
> +    kidnap_status_topic: /kidnap_status
This is already defined in `kidnap_estimator_params.yaml`. Shouldn't it be removed?

2021-12-13 15:32 UTC, eborghi10 commented on irobot_create_common_bringup/config/robot_state_params.yaml
> +    undocked_charge_limit: 0.03
```suggestion
    undocked_charge_limit: 0.03

```

2021-12-13 15:32 UTC, eborghi10 commented on irobot_create_toolbox/include/irobot_create_toolbox/kidnap_estimator_publisher.hpp
> +protected:
Why not `private`?

2021-12-13 15:37 UTC, eborghi10 requested changes
I left some changes. I cannot test it because my Galactic image is not working.

2021-12-13 19:03 UTC, LolaSegura commented on irobot_create_toolbox/include/irobot_create_toolbox/kidnap_estimator_publisher.hpp
> +protected:
You are right, this could be private, I changed it.

2021-12-14 15:12 UTC, alsora commented on irobot_create_toolbox/include/irobot_create_toolbox/kidnap_estimator_publisher.hpp
> +  void kidnap_callback(irobot_create_msgs::msg::HazardDetectionVector::SharedPtr msg);
minor: the callback does not need to be public, the same applies to `dock_callback` and `stop_callback` in the robot-state node

2021-12-15 17:23 UTC, alsora approved these changes

2021-12-15 18:11 UTC, merged