Implements the kidnap status using lambda functions.
iRobotEducation/create3_sim pull request #128
Opened 2021-11-03 14:36 UTC by LolaSegura

## Description

This changes the kidnap status callback implementation using a lambda function. 

Solves item 4 of #106.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Test it
Launch the robot using an empty world
``` #bash
   ros2 launch irobot_create_gazebo create3.launch.py 
```
in a new terminal source and check that the kidnap status works as expected. The robot is consider kidnapped if both wheel drops and the four cliff sensors are activated. 

``` #bash
   . install/local_setup.bash
   ros2 topic echo /kidnap_status
```

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2021-11-03 23:38 UTC, alsora approved these changes

2021-11-11 12:28 UTC, rjcausarano reviewed
I think the code looks mostly good, but can you please fix the merge conflict so that I can test it?

2021-11-11 12:28 UTC, rjcausarano commented on irobot_create_gazebo/launch/create3.launch.py
> +    robot_state_yaml_file = PathJoinSubstitution(
status

2021-11-11 12:28 UTC, rjcausarano commented on irobot_create_gazebo/launch/create3.launch.py
> +    robot_state_node = Node(
status

2021-11-11 17:11 UTC, LolaSegura commented on irobot_create_gazebo/launch/create3.launch.py
> +    robot_state_yaml_file = PathJoinSubstitution(
As we talked on the PR #127 I called everything state

2021-11-11 17:11 UTC, LolaSegura commented on irobot_create_gazebo/launch/create3.launch.py
> +    robot_state_node = Node(
Same as previous comment

2021-11-11 17:12 UTC, LolaSegura commented
> I think the code looks mostly good, but can you please fix the merge conflict so that I can test it?

I resolved the merge conflicts

2021-11-16 18:35 UTC, eborghi10 commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +  kidnap_status_msg_.is_kidnapped = wheel_drop_count >= 2 && cliff_sensor_count >= 4;
Should `2` and `4` be class members or modifiable via ROS parameters?

2021-11-29 14:59 UTC, LolaSegura commented on irobot_create_toolbox/src/robot_state_publisher.cpp
> +  kidnap_status_msg_.is_kidnapped = wheel_drop_count >= 2 && cliff_sensor_count >= 4;
Addressed

2021-11-29 15:14 UTC, eborghi10 commented
@LolaSegura the commit list seems long because you added commits from `main`. Was this expected?

2021-11-29 15:30 UTC, LolaSegura commented
> @LolaSegura the commit list seems long because you added commits from `main`. Was this expected?

You are right, It was not expected, I should have rebased from the base branch not from `main`.  I will fix this.

2021-12-17 21:06 UTC, eborghi10 requested changes

2021-12-17 21:06 UTC, eborghi10 commented on irobot_create_toolbox/include/irobot_create_toolbox/kidnap_estimator_publisher.hpp
> +  const int min_cliff_sensor_count_ = 4;
```suggestion
  const int min_wheel_drop_count_{2};
  const int min_cliff_sensor_count_{4};
```

2021-12-17 21:06 UTC, eborghi10 commented on irobot_create_toolbox/src/kidnap_estimator_publisher.cpp
> +  auto cliff_sensor_count = std::count_if(
Nice approach!

2021-12-17 21:06 UTC, eborghi10 commented on irobot_create_toolbox/src/kidnap_estimator_publisher.cpp
> +  // and the four cliff sensors are triggered.
```suggestion
  // and four cliff sensors are triggered.
```

2021-12-17 21:06 UTC, eborghi10 commented on irobot_create_common_bringup/config/robot_state_params.yaml
> +    lightring_topic: /cmd_lightring
I think you need to rebase this branch with `main` again. You're introducing 12 commits and these changes seem to be unintended.

We can sync offline on Monday, but I'd create the branch again and cherry-pick the commit with the specific changes.

2021-12-18 08:35 UTC, alsora commented
The approach looks good to me.
I agree that there are some wrongly resolved merge conflicts in the diff.

2021-12-20 12:53 UTC, LolaSegura commented on irobot_create_common_bringup/config/robot_state_params.yaml
> +    lightring_topic: /cmd_lightring
That'll be great, thanks!

2021-12-21 14:42 UTC, alsora approved these changes

2021-12-21 14:44 UTC, eborghi10 requested changes

2021-12-21 14:44 UTC, eborghi10 commented on irobot_create_toolbox/include/irobot_create_toolbox/kidnap_estimator_publisher.hpp
> +  const int min_cliff_sensor_count_{4};
```suggestion
  const std::size_t min_wheel_drop_count_{2};
  const std::size_t min_cliff_sensor_count_{4};
```

2021-12-21 17:50 UTC, eborghi10 approved these changes

2021-12-21 18:11 UTC, merged