Add Launch arguments to enable/disable visualization of rays
iRobotEducation/create3_sim pull request #139
Opened 2021-12-20 20:12 UTC by Ednip7

## Description

- Added argument to create3_gazebo.launch.py and robot_description.launch.py to enable/disable the visualization of cliff sensors.
- Modified create3.urdf.xacro to receive added argument.

Fixes #100 .

## How Has This Been Tested?

To enable visualization rays, run:
```bash
ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py visulize_rays:=true
```
To disable visualization rays, run:
```bash
ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py visulize_rays:=false
```

2021-12-20 21:03 UTC, alsora commented
Should the visualize flag be applied also to the dock urdf ? (in particular to the ir_emitters file)

2021-12-21 11:15 UTC, eborghi10 requested changes

2021-12-21 11:15 UTC, eborghi10 commented on irobot_create_common_bringup/launch/robot_description.launch.py
> +                          choices=['true', 'false'],
It seems like the arguments are not aligned.

2021-12-21 11:15 UTC, eborghi10 commented on irobot_create_description/urdf/create3.urdf.xacro
> +  <xacro:arg name="visualize_rays" default="false"/>
```suggestion

  <xacro:arg name="visualize_rays" default="false"/>

```

2021-12-21 11:15 UTC, eborghi10 commented on irobot_create_description/urdf/create3.urdf.xacro
> +  <xacro:cliff_sensor name="front_right" visualize="$(arg visualize_rays)">
Shouldn't this change be also applied to the `cliff_sensor` macro?

2021-12-21 11:15 UTC, eborghi10 commented on irobot_create_gazebo_bringup/launch/create3_gazebo.launch.py
> +    DeclareLaunchArgument('visualize_rays', default_value='false',
There's no need to declare the launch argument here and in `robot_description.launch.py`. Please double-check.

2021-12-21 11:21 UTC, alsora commented on irobot_create_gazebo_bringup/launch/create3_gazebo.launch.py
> +    DeclareLaunchArgument('visualize_rays', default_value='false',
+1 on this.
If possible, this launch argument should only be declared close to where it's actually used, especially considering that it's mostly a debug feature

2021-12-23 11:51 UTC, eborghi10 requested changes

2021-12-23 11:51 UTC, eborghi10 commented on irobot_create_common_bringup/launch/dock_description.launch.py
> +    pkg_create3_description = get_package_share_directory(
Why did you make this change?

2021-12-23 11:51 UTC, eborghi10 commented on irobot_create_common_bringup/launch/dock_description.launch.py
> +        'y'), LaunchConfiguration('z')
In case you have to put this in a new line, consider initializing the 3 variables in different lines directly.

2021-12-23 11:51 UTC, eborghi10 commented on irobot_create_common_bringup/launch/robot_description.launch.py
> +                          choices=['true', 'false'],
@Ednip7 please click on "Resolve conversation" once you address comments.

2022-01-06 13:33 UTC, eborghi10 approved these changes

2022-01-06 15:14 UTC, alsora approved these changes

2022-01-06 15:15 UTC, alsora commented
Looks good to me.
@Ednip7 apparently there are some test failures.
You can run tests locally with 
```
colcon build
colcon test
```

2022-01-20 16:31 UTC, eborghi10 commented
Is this ready for another review, @Ednip7? CC @lchico

2022-01-20 16:55 UTC, Ednip7 commented
> Is this ready for another review, @Ednip7? CC @lchico

Yes! It is! PTAL guys!

2022-01-21 14:01 UTC, eborghi10 approved these changes

2022-01-21 14:54 UTC, alsora approved these changes

2022-01-24 13:22 UTC, lchico commented
Good job! @Ednip7
Just some minors comment,  check on your description:
Typo:
ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py **visulize_rays**:=true
Modified create3.urdf.xacro and standard_dock.urdf.**zacro** to receive arguments.

@eborghi10 Should we make this argument appear when we run:
`ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py --show-arguments`

2022-01-24 13:29 UTC, eborghi10 commented
> Should we make this argument appear when we run: `ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py --show-arguments`

@lchico aren't you seeing the argument? It should be there. If not, it's because the argument is not in the main launch file. I wouldn't worry about that, it's not an important argument. We use it mainly for debugging purposes.

2022-01-24 13:30 UTC, eborghi10 commented
@Ednip7 can you post a screenshot with how the simulated robot looks like in the PR description?

2022-01-25 12:12 UTC, lchico approved these changes
LGTM!

2022-01-25 12:22 UTC, merged